DROP SEQUENCE FILESEQ

CREATE SEQUENCE FILESEQ
AS INT               --int 정수형
START WITH 1		 -- 시작 값 0부터
INCREMENT BY 1       -- 증가 값 +1
MINVALUE -2147483648 --최소값 int 크기
MAXVALUE 2147483647  --최대값
-- NO CACHE OR CACHE
CACHE

DROP TABLE FILETEST;

CREATE TABLE FILETEST (
	FILENAME VARCHAR(500), -- 중복되어 변경된 파일명
	FILEREALNAME VARCHAR(500), -- 사용자가 실제로 업로드한 파일명
	EXTENTION VARCHAR(50), -- 확장자
	FILESIZE BIGINT, -- 파일 크기
	DOWNCOUNT INT, -- 다운로드 횟수
	SEQ INT PRIMARY KEY DEFAULT NEXT VALUE FOR FILESEQ -- pk
);

-- table comment
EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'SERVER 파일업로드 TEST TABLE', 'USER', DBO, 'TABLE', FILETEST;

-- column comment
EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '중복되어 변경된 파일명', 'USER', DBO, 'TABLE', FILETEST, 'COLUMN', FILENAME;
EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '사용자가 실제로 업로드한 파일명', 'USER', DBO, 'TABLE', FILETEST, 'COLUMN', FILEREALNAME;
EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '확장자', 'USER', DBO, 'TABLE', FILETEST, 'COLUMN', EXTENTION;
EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '파일 크기', 'USER', DBO, 'TABLE', FILETEST, 'COLUMN', FILESIZE;
EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '다운로드 횟수', 'USER', DBO, 'TABLE', FILETEST, 'COLUMN', DOWNCOUNT;
EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'PK', 'USER', DBO, 'TABLE', FILETEST, 'COLUMN', SEQ;

