DROP TABLE FILETEST_PARK


CREATE TABLE FILETEST_PARK (
	GRPKIND VARCHAR(500) NOT NULL, --PRIMARY KEY,
	SSKEYCODE VARCHAR(500) NOT NULL, --  PRIMARY KEY,
	FILENAME VARCHAR(500) NOT NULL,
	FILEREALNAME VARCHAR(500) NOT NULL,
	FILESIZE VARCHAR(500),
	EXTENTION VARCHAR(500),
	UPLOADUSER VARCHAR(500),
	UPLOADDATE DATETIME,
	DOWNCOUNT INT -- 다운로드 횟수
)

SELECT * FROM FILETEST_PARK

EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '전표 파일업로드 테이블', 'USER', DBO, 'TABLE', FILETEST_PARK; -- 테이블 설명

EXEC   SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', GRPKIND; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '전표 KEY 값', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', SSKEYCODE; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '저장된파일명', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', FILENAME; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '실제파일명', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', FILEREALNAME; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '파일크기', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', FILESIZE; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '파일확장자', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', EXTENTION; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '업로드유저', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', UPLOADUSER; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '업로드일', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', UPLOADDATE; -- 컬럼 코멘트
EXEC   SP_ADDEXTENDEDPROPERTY '다운로드횟수', '회사코드', 'USER', DBO, 'TABLE', FILETEST_PARK, 'COLUMN', DOWNCOUNT; -- 컬럼 코멘트

ALTER TABLE FILETEST_PARK DROP CONSTRAINT PK_FILE

ALTER TABLE FILETEST_PARK ADD CONSTRAINT PK_FILE PRIMARY KEY(GRPKIND, SSKEYCODE)


/* 요구사항 */
/*
1. 전표삭제시 트리거 또는 로직으로 해당 file table의 sskeycode 값으로 삭제
	(해당 물리 파일도 삭제)

2. 다중 업로드, 다중 다운로드, 다중 삭제

3. file 형식의 구애 받지 않음
*/





/*
grid.js

fileChooser
setFileUpForm => multifile upload form을 수정
fileUploadSuccess


$('#mFileUploadLayer').show(); ==> grid에서의 파일첨부임
*/